-- Demo users for testing the authentication system
-- Passwords are encoded with BCrypt (the actual encoded values will be generated by the application)
-- Plain text passwords: admin123, teacher123, student123, parent123

USE homework_db;

-- Insert demo users (Note: passwords will be automatically encoded by the Spring Security BCryptPasswordEncoder)
-- These INSERT statements should be run after the application starts for the first time
-- Or you can use the registration endpoints to create these users

-- Admin User
INSERT INTO users (first_name, last_name, email, password, role, phone_number, is_active, created_at, updated_at) 
VALUES ('Admin', 'User', 'admin@homework.com', '$2a$10$rJ8jQRKE.rF8.Q8Q8Q8Q8O8Q8Q8Q8Q8Q8Q8Q8Q8Q8Q8Q8Q8Q8Q8Q8', 'ADMIN', '123-456-7890', true, NOW(), NOW());

-- Teacher User
INSERT INTO users (first_name, last_name, email, password, role, phone_number, subject_taught, is_active, created_at, updated_at) 
VALUES ('John', 'Smith', 'teacher@homework.com', '$2a$10$rJ8jQRKE.rF8.Q8Q8Q8Q8O8Q8Q8Q8Q8Q8Q8Q8Q8Q8Q8Q8Q8Q8Q8Q8', 'TEACHER', '123-456-7891', 'Mathematics', true, NOW(), NOW());

-- Student User
INSERT INTO users (first_name, last_name, email, password, role, phone_number, class_grade, student_id, is_active, created_at, updated_at) 
VALUES ('Emma', 'Johnson', 'student@homework.com', '$2a$10$rJ8jQRKE.rF8.Q8Q8Q8Q8O8Q8Q8Q8Q8Q8Q8Q8Q8Q8Q8Q8Q8Q8Q8Q8', 'STUDENT', '123-456-7892', '3rd Grade', 'STU001', true, NOW(), NOW());

-- Parent User
INSERT INTO users (first_name, last_name, email, password, role, phone_number, class_grade, parent_of_student_id, is_active, created_at, updated_at) 
VALUES ('Michael', 'Johnson', 'parent@homework.com', '$2a$10$rJ8jQRKE.rF8.Q8Q8Q8Q8O8Q8Q8Q8Q8Q8Q8Q8Q8Q8Q8Q8Q8Q8Q8Q8', 'PARENT', '123-456-7893', '3rd Grade', 'STU001', true, NOW(), NOW());

-- Additional demo users
INSERT INTO users (first_name, last_name, email, password, role, phone_number, subject_taught, is_active, created_at, updated_at) 
VALUES ('Sarah', 'Wilson', 'sarah.teacher@homework.com', '$2a$10$rJ8jQRKE.rF8.Q8Q8Q8Q8O8Q8Q8Q8Q8Q8Q8Q8Q8Q8Q8Q8Q8Q8Q8Q8', 'TEACHER', '123-456-7894', 'English', true, NOW(), NOW());

INSERT INTO users (first_name, last_name, email, password, role, phone_number, class_grade, student_id, is_active, created_at, updated_at) 
VALUES ('Alex', 'Brown', 'alex.student@homework.com', '$2a$10$rJ8jQRKE.rF8.Q8Q8Q8Q8O8Q8Q8Q8Q8Q8Q8Q8Q8Q8Q8Q8Q8Q8Q8Q8', 'STUDENT', '123-456-7895', '4th Grade', 'STU002', true, NOW(), NOW());

INSERT INTO users (first_name, last_name, email, password, role, phone_number, class_grade, student_id, is_active, created_at, updated_at) 
VALUES ('Sophia', 'Davis', 'sophia.student@homework.com', '$2a$10$rJ8jQRKE.rF8.Q8Q8Q8Q8O8Q8Q8Q8Q8Q8Q8Q8Q8Q8Q8Q8Q8Q8Q8Q8', 'STUDENT', '123-456-7896', '3rd Grade', 'STU003', true, NOW(), NOW());

-- Note: The above password hashes are placeholders. 
-- For testing, it's recommended to:
-- 1. Start the application
-- 2. Use the registration endpoint to create demo users with plain text passwords
-- 3. The application will automatically hash the passwords using BCrypt

-- Demo credentials for manual testing:
-- Email: admin@homework.com, Password: admin123
-- Email: teacher@homework.com, Password: teacher123  
-- Email: student@homework.com, Password: student123
-- Email: parent@homework.com, Password: parent123 